project:
  type: website
  output-dir: docs 

website:
  title: "MATH283 Project Three Collab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reactor_cooling_model_pt_1.qmd
        text: Brainstorm 1-4
