project:
  type: website
  output-dir: docs 

website:
  title: "MATH283 Project Three Collab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reactor_cooling_model_pt_1.qmd
        text: Brainstorm 1
      - href: brainstorm_2.qmd
        text: Brainstorm 2
      - href: brainstorm_3.qmd
        text: Brainstorm 3
      - href: U03_REPORT.qmd
        text: U03_REPORT
      - href: CH_3_PROB_7_example.qmd
        text: Chapter Three, Problem Seven (HW Presentation)
  page-footer: 
    border: true
    left: "Corey Silver and Parker Lee BYU-I 2026©"
format:
  html:
    toc: true
    # number-sections: true
    # number-depth: 3
    code-fold: true
    code-summary: "Reveal Secrets"
    theme: default   # This strips out the default
    css: styles.css  
