---
title: "Reactor Cooling: A Toybox Engineering Safety Model"
---

Follow the 8-step modeling process as you brainstorm with your team.  When you write up your final report be sure to use section headers, well developed paragraphs, well labeled graphs, clear explanations of the mathematics, etc. Unit 03 Report will be a Team Report.  For this assignment (U03 Modeling Process and Collaboration Part I) turn in your brainstorming for steps 1-4 of the process.

### Scenario: Cooling Performance During Reactor Shutdown

Engineers are studying how quickly reactor components cool following shutdown.

# Measurements:

| Time after Shutdown ($\text{hr}$) | Temperature $(^\circ C)$|
|---------|:-----|
| 1 | 580 |
| 2 | 510 | 
| 4 | 430 |
| 8 | 340 |
|12 | 290 |
|18 | 230 |


A large prediction error could affect cooling procedures and operational decisions.

Your team has been asked to recommend the best model and fitting strategy.


# Step 1: Identify the problem

We need to reliably predict the temperature of the reactor (in K) from the time passed since shutoff (in minutes).


# Step 2: Assumptions

1. bulk cooling rate/single substance component
2. constant external temperature
3. No other heat sources
4. Reactor isn't operated until cooling is complete

# Step 3: Variables and Parameters

$T_R$ is the reactor temperature.

$T_E$ is the external tremperature

$t$ is the time from shutdown in hours.

That's it! While a high-fidelity model would and could account for the specific heats of individual reactor components, the role of humidity in cooling, and the stochastic nature of thermodynamic processes, this problem is small in scope. We will start, at least, from a basic model of heat transfer. This is most appropriate for the limited data we have on the situation.



# Step 4: Model Development
We'll test optimized Chebyshev, Least-Squares, and Absolute-Deviation fits of the following models: 
## Linear:

Of form $T(t)=c_1\cdot t + c_2$.

## Polynomial: 

Of form $T(t)=c_1t^n + c_2t^{n-1} +...+c_kt^0$. 

We'll limit $n$ and $k$ to three or four, at most, since we don't want to overfit.

## Exponential decay:

Of form $T(t) = (c_2)e^{c_1t}$ ($c_2$ is negative).

We'll linearize this so that it can be optimized with linear programming. taking the natural log of both sides give us

$\ln[T(t)]=c_1t+c_2$

## Step 5: Analysis and Optimization.

Writing a python function to peform analysis and optimization. 


## Step 6: Prediction

After 24 hours, the 

## Bibliography (wip):

1. Dawkins, Paul. "The Heat Equation." Paul's Online Notes, Lamar University, tutorial.math.lamar.edu/classes/de/theheatequation.aspx. Accessed 26 May 2026.

1. "File:Maine Yankee Nuclear Power Plant.jpg." Wikimedia Commons. 12 Dec 2024, 03:31 UTC. <https://commons.wikimedia.org/w/index.php?title=File:Maine_Yankee_Nuclear_Power_Plant.jpg&oldid=969140195> 3 Jun 2026, 05:02. 
