---
title: "Unit 3 Report: Nuclear Reactor Cooling Timeline"
format: html
jupyter: python3
highlight-style: default
code-block-bg: "#000000"
filters:
    - shinylive
---
# Unit 3 Modeling Report
## Corey Silver and Parker Lee
### Scenario: Cooling Performance During Reactor Shutdown

Engineers are studying how quickly reactor components cool following shutdown.

# 1. Measurements:

| Time after Shutdown ($\text{hr}$) | Temperature $(^\circ C)$|
|---------|:-----|
| 1 | 580 |
| 2 | 510 | 
| 4 | 430 |
| 8 | 340 |
|12 | 290 |
|18 | 230 |

```{python}

import matplotlib.pyplot as plt
import numpy as np
import scipy as sci
import pandas as pd
import IPython.display as ipd
from shinylive import *
from data_fitting import *

X = [1, 2, 4, 8, 12, 18]
# See section 4 for explanation of modification of T data.
Y = [1.05*y for y in [580, 510, 430, 340, 290, 230]]

```

"A large prediction error could affect cooling procedures and operational decisions.

Your team has been asked to recommend the best model and fitting strategy."


# 2. Objective Definition

We need to reliably predict the temperature of the reactor (in K) from the time passed since shutoff (in minutes). Since this is a live nuclear reactor, criticality is a prime safety concern.


# 3. Assumptions and Simplifications

In any mathematical model, there are certain assumptions made and simplifications accepted. For this model, we keep in mind the sensitive nature of the system in question, which leades us to an overarching principle which we'll follow throughout this modelling process.

## Our first and central assumption is that of the *worst-case scenario*: we assume the least optimal conditions, in every case, for time to cooling. For example, when we assume a constant external temperature, we assume that temperature to be the mean daily maximum for the season in which we operate.

1. Bulk, uniform cooling rate: no regions of greater $T$ density
1. Single substance component: single specific heat
1. Constant external temperature
1. Constant external humidity, pressure: We assume no weather.
1. We assume the absence of other heat sources, ignoring the effect of sunlight.
1. Reactor isn't operated until cooling is complete
1. We assume a $+5{\%}$ margin of error with temperature measurement. This will be one in a group of safety redundancies. 

# 5. Variables and Parameters

$T_R$ is the reactor temperature.

$T_E$ is the external tremperature

$t$ is the time from shutdown in hours.

That's it! While a high-fidelity model would and could account for the specific heats of individual reactor components, the role of humidity in cooling, and the stochastic nature of thermodynamic processes, we can simplify extensively for the purpose of this problem. First, we're supplied with cooling and time data; this means that we must assume similar external conditions throughout the cooling period in order to use this supplied data for interpolation and limited extrapolation. Second, we can justify some simplification from the safety-focused nature of the model we're designing. We do not know the external conditions for the data we're given, so the most prudent approach is to assume that these conditions are favorable to quick cooling and consider them optimized.  We will start, at least, from a basic model of heat transfer. This is most appropriate for the limited data we have on the situation.

# Model Development
We'll test optimized Chebyshev, Least-Squares, and Absolute-Deviation fits of the following models: 

## Linear:

Of form $T(t)=c_1\cdot t + c_2$.

```{python}

poly_deg = 1

plotter(X, Y, "linear", 1)
```

## Polynomial: 

Of form $T(t)=c_1t^n + c_2t^{n-1} +...+c_kt^0$. 

We'll limit $n$ and $k$ to four or five, at most. Any higher and at that point we'd be overfitting to approximate a power curve. Please use the slider below to observe the effect of polynomial degree on fit parameters and optimization quality

```{shinylive-python}
#| standalone: true
#| viewerHeight: 500

"""
code modified from example in docs at https://quarto-ext.github.io/shinylive/
This gemini conversation used for debugging and editing:                                              
https://gemini.google.com/share/59ac2467bf7b                                  
"""

from data_fitting import *
from shiny import *
import shinywidgets as shw

app_ui = ui.page_fluid(
    ui.layout_columns(
        ui.input_slider("n", "Degree of Polynomial Fit:", min=1, max=6, value = 2),
        ui.output_plot("conspiracy", width = 10, height = 20), 
    )
)
poly_deg = input.n
def server(input: Inputs, output: Outputs, session: Session):
    @render.plot
    def conspiracy():
        return plotter(X, Y, "polynomial", poly_deg)


app = App(app_ui, server)

## file: data_fitting.py
{{< include data_fitting.py >}}

## file: requirements.txt
matplotlib
numpy
scipy
pandas
IPython
```

## Exponential decay:

Of form $T(t) = (c_2)e^{c_1t}$ ($c_2$ is negative).

We'll linearize this so that it can be optimized with linear programming. taking the natural log of both sides gives us

$$
\ln[T(t)]=c_1t+c_2.
$$

## Power model:

Of form $T(t) = (c_2)^{c_1t}$

We'll linearize this sort of model in the same way, also giving us

$$
\ln[T(t)]=c_1t+c_2.
$$

# Bibliography

1. "4.2A Newton's Law of Cooling." Ximera, The Ohio      State University, ximera.osu.edu/ode/main/lawOfCooling/lawOfCooling. Accessed 15 June 2026.
